//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificationAutomation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertificationAutomation.Resources.ObjectMap", typeof(ObjectMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_MainContent_accountSegmentsDataList_ctl01_txtAccountSegment.
        /// </summary>
        internal static string Account_Textbox {
            get {
                return ResourceManager.GetString("Account_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_MainContent_txtAccName.
        /// </summary>
        internal static string AccountName_Textbox {
            get {
                return ResourceManager.GetString("AccountName_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@id=&quot;menu_mega&quot;]/li[2]/div/ul[1]/li[3]/a.
        /// </summary>
        internal static string Add_New_Account {
            get {
                return ResourceManager.GetString("Add_New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@id=&quot;column1_cert&quot;]/div/div/div/div/div/div/h3/a.
        /// </summary>
        internal static string Certification_R2R_Header {
            get {
                return ResourceManager.GetString("Certification_R2R_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_MainContent_accountSegmentsDataList_ctl00_txtAccountSegment.
        /// </summary>
        internal static string CompanyCode_Textbox {
            get {
                return ResourceManager.GetString("CompanyCode_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trintech.
        /// </summary>
        internal static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00$MainContent$descriptionTextBox_Div.
        /// </summary>
        internal static string Description_Textbox {
            get {
                return ResourceManager.GetString("Description_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_MainContent_accountSegmentsDataList_ctl02_txtAccountSegment.
        /// </summary>
        internal static string Division_Textbox {
            get {
                return ResourceManager.GetString("Division_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id:Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css:input[value=&apos;Sign In&apos;].
        /// </summary>
        internal static string Login_SignInButton {
            get {
                return ResourceManager.GetString("Login_SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id:UserName.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath://*[@id=&quot;menu_mega&quot;]/li[2]/a[2].
        /// </summary>
        internal static string Maintenance_Tab {
            get {
                return ResourceManager.GetString("Maintenance_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctl00_MainContent_accountSegmentsDataList_ctl03_txtAccountSegment.
        /// </summary>
        internal static string SetofBooks_Textbox {
            get {
                return ResourceManager.GetString("SetofBooks_Textbox", resourceCulture);
            }
        }
    }
}
